name: Build App with tests and Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test-app:
    name: Build application and test it
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: generate-openapi-objects
        run: mvn -f ModelsGenerator/pom.xml -B clean compile

      - name: Build with maven
        run: mvn -f Backend/pom.xml -B clean verify

  build-docker:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: build-and-test-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t spring-boot-app:test .